<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>aub</groupId>
  <artifactId>iso</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <properties>
    <maven.compiler.source>19</maven.compiler.source>
    <maven.compiler.target>19</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>iso.Main</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-core</artifactId>
      <version>1.5.2</version>
    </dependency>
    <dependency>
      <groupId>org.ejml</groupId>
      <artifactId>ejml-core</artifactId>
      <version>0.44.0</version>
    </dependency>
    <dependency>
      <groupId>org.ejml</groupId>
      <artifactId>ejml-ddense</artifactId>
      <version>0.44.0</version>
    </dependency>
    <dependency>
      <groupId>org.ejml</groupId>
      <artifactId>ejml-all</artifactId>
      <version>0.44.0</version>
    </dependency>
    <dependency>
      <groupId>org.ojalgo</groupId>
      <artifactId>ojalgo</artifactId>
      <version>56.2.1</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>